<?php
/**
 * Urdu Books World - Installation Script
 * Initializes the database and registers the admin user.
 */

define('LOCK_FILE', __DIR__ . '/install.lock');

// Prevent running if lock file exists
if (file_exists(LOCK_FILE)) {
    die("Installation already completed. If you wish to re-install, please delete the file '/admin/install.lock' via your hosting file manager.");
}

$error_msg = '';
$success_msg = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['install_submit'])) {
    $db_host = trim($_POST['db_host'] ?: 'localhost');
    $db_name = trim($_POST['db_name']);
    $db_user = trim($_POST['db_user']);
    $db_pass = $_POST['db_pass'];
    $site_url = rtrim(trim($_POST['site_url'] ?: ''), '/');
    
    $admin_email = trim($_POST['admin_email']);
    $admin_pass = $_POST['admin_pass'];
    
    if (empty($db_name) || empty($db_user) || empty($admin_email) || empty($admin_pass) || empty($site_url)) {
        $error_msg = 'Please fill in all database name, database user, and administrator details.';
    } elseif (!filter_var($site_url, FILTER_VALIDATE_URL)) {
        $error_msg = 'Please enter a valid public website URL.';
    } elseif (strlen($admin_pass) < 6) {
        $error_msg = 'Admin password must be at least 6 characters long.';
    } else {
        
        // 1. Attempt connection
        try {
            $dsn = "mysql:host=$db_host;charset=utf8mb4";
            $pdo = new PDO($dsn, $db_user, $db_pass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
            ]);
            
            // Create database if not exists
            $pdo->exec("CREATE DATABASE IF NOT EXISTS `$db_name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            $pdo->exec("USE `$db_name`");
            
            // 2. Load and Import Schema
            $schema_file = dirname(__DIR__) . '/sql/schema.sql';
            if (!file_exists($schema_file)) {
                throw new Exception("Could not find '/sql/schema.sql'. Please ensure you uploaded all files.");
            }
            $schema_sql = file_get_contents($schema_file);
            $pdo->exec($schema_sql);
            
            // 3. Load and Import Seeds
            $seed_file = dirname(__DIR__) . '/sql/seed.sql';
            if (!file_exists($seed_file)) {
                throw new Exception("Could not find '/sql/seed.sql'.");
            }
            $seed_sql = file_get_contents($seed_file);
            $pdo->exec($seed_sql);
            
            // 4. Update the Admin User Details
            $admin_hash = password_hash($admin_pass, PASSWORD_BCRYPT);
            // Delete existing admin records from seed
            $pdo->exec("DELETE FROM users WHERE role = 'admin' OR id = 1");
            
            // Insert fresh admin
            $stmt = $pdo->prepare("INSERT INTO users 
                (id, email, password_hash, first_name, last_name, phone, role, is_active) 
                VALUES (1, ?, ?, 'Store', 'Administrator', '+447123456789', 'admin', 1)");
            $stmt->execute([$admin_email, $admin_hash]);
            
            // 5. Write server-only local configuration
            $config_content = "<?php
/**
 * Urdu Books World - Server Local Configuration
 * Auto-generated by install.php on " . date('Y-m-d H:i:s') . "
 */

return [
    'DB_HOST' => '" . addslashes($db_host) . "',
    'DB_NAME' => '" . addslashes($db_name) . "',
    'DB_USER' => '" . addslashes($db_user) . "',
    'DB_PASS' => '" . addslashes($db_pass) . "',
    'SITE_URL' => '" . addslashes($site_url) . "',
];
";
            
            $config_file = dirname(__DIR__) . '/includes/config.local.php';
            file_put_contents($config_file, $config_content);
            
            // 6. Write Lock file to self-disable
            file_put_contents(LOCK_FILE, "Installed on " . date('Y-m-d H:i:s'));
            
            $success_msg = 'Database tables imported, settings loaded, and administrator account created successfully! The installer has now disabled itself.';
            
        } catch (Exception $e) {
            $error_msg = 'Database connection failed or Import Error: ' . $e->getMessage();
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Urdu Books World - Website Installer</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        :root {
            --maroon: #7B1E2B;
            --gold: #D4A24C;
            --bg: #FAF8F4;
            --text: #1A1A1A;
            --white: #FFFFFF;
        }
        body {
            font-family: 'Inter', sans-serif;
            background-color: var(--bg);
            color: var(--text);
            margin: 0;
            padding: 40px 20px;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background-color: var(--white);
            border-radius: 8px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.08);
            padding: 40px;
        }
        .brand-header {
            text-align: center;
            margin-bottom: 30px;
        }
        .brand-title {
            color: var(--maroon);
            margin: 0;
            font-size: 24px;
            font-weight: 700;
        }
        .brand-title span {
            color: var(--gold);
        }
        .form-group {
            margin-bottom: 20px;
        }
        label {
            display: block;
            margin-bottom: 8px;
            font-weight: 500;
            font-size: 14px;
        }
        input, select {
            width: 100%;
            padding: 10px 12px;
            border: 1px solid #DDDDDD;
            border-radius: 4px;
            box-sizing: border-box;
            font-family: inherit;
        }
        input:focus {
            border-color: var(--maroon);
            outline: none;
        }
        .btn {
            background-color: var(--maroon);
            color: var(--white);
            border: none;
            padding: 12px 20px;
            font-weight: 600;
            font-size: 15px;
            width: 100%;
            border-radius: 4px;
            cursor: pointer;
        }
        .btn:hover {
            background-color: #5c141d;
        }
        .alert {
            padding: 12px 15px;
            border-radius: 4px;
            margin-bottom: 20px;
            font-size: 14px;
        }
        .alert-danger {
            background-color: #FDEDED;
            color: #D32F2F;
            border: 1px solid #F8C4C4;
        }
        .alert-success {
            background-color: #EDF7ED;
            color: #1E4620;
            border: 1px solid #C8E6C9;
        }
        hr {
            border: none;
            border-top: 1px solid #EEEEEE;
            margin: 25px 0;
        }
    </style>
</head>
<body>

    <div class="container">
        <div class="brand-header">
            <h1 class="brand-title">URDU <span>BOOKS</span> WORLD</h1>
            <p>Website Installer</p>
        </div>

        <?php if (!empty($error_msg)): ?>
            <div class="alert alert-danger">
                <i class="fa fa-exclamation-circle"></i> <?php echo htmlspecialchars($error_msg); ?>
            </div>
        <?php endif; ?>
        <?php if (!empty($success_msg)): ?>
            <div class="alert alert-success">
                <i class="fa fa-check-circle"></i> <?php echo htmlspecialchars($success_msg); ?>
            </div>
            <div style="text-align: center;">
                <a href="<?php echo SITE_URL; ?>/admin/login.php" class="btn" style="text-decoration:none; display:inline-block;">Proceed to Admin Log-in</a>
            </div>
        <?php else: ?>
            <form action="install.php" method="POST">
                <h3 style="margin-top:0;">1. Website URL</h3>
                <div class="form-group">
                    <label>Public Site URL *</label>
                    <input type="url" name="site_url" required value="<?php echo htmlspecialchars(((!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http') . '://' . ($_SERVER['HTTP_HOST'] ?? 'urdubooksworld.co.uk')); ?>">
                </div>

                <hr>

                <h3>2. Database Server Connection</h3>
                <div class="form-group">
                    <label>Database Host</label>
                    <input type="text" name="db_host" value="localhost">
                </div>
                <div class="form-group">
                    <label>Database Name *</label>
                    <input type="text" name="db_name" required placeholder="e.g. u123456_urdubooks">
                </div>
                <div class="form-group">
                    <label>Database User *</label>
                    <input type="text" name="db_user" required placeholder="e.g. u123456_user">
                </div>
                <div class="form-group">
                    <label>Database Password</label>
                    <input type="password" name="db_pass" placeholder="Database user password">
                </div>

                <hr>

                <h3>3. Create Administrator Account</h3>
                <div class="form-group">
                    <label>Administrator Email *</label>
                    <input type="email" name="admin_email" required placeholder="admin@urdubooksworld.co.uk">
                </div>
                <div class="form-group">
                    <label>Administrator Password *</label>
                    <input type="password" name="admin_pass" required minlength="6" placeholder="Choose a secure password">
                </div>

                <div style="margin-top: 30px;">
                    <button type="submit" name="install_submit" class="btn">Run Setup &amp; Import Tables</button>
                </div>
            </form>
        <?php endif; ?>
    </div>

</body>
</html>
